### ISSUE TITLE
Add support for `nullable` at least in request body params

### ISSUE THREAD

**Issue by gimenete** [cloudflare/itty-router-openapi#87]
I've found myself needing a request body param to be either a string or null in a `PATCH` request. There's a `required` option, which means the param can be omited, but what I need is a explicit way to set a value as `null`, specially because I'm using `PATCH` to do partial updates or records in the database.

So far I've been using empty strings as a way to indicate that, but it's not ideal. It's confusing for the users of my API.

Thanks!

**Comment by G4brym** [comment]
Hey @gimenete thats a issue that is being fixed in the new v1.0 version, this new version also brings support for zod everywhere

i'm not sure when are we going to release this new version, but you can already try it out by installing the prerelease version in the [pr here](https://github.com/cloudflare/itty-router-openapi/pull/77)

We are already using this new pre release version for our production workloads, and i don't expect the api to change anymore before the release

**Comment by G4brym** [comment]
Hey @gimenete, i've just published the new v1.0.0 release that fixes this issue, not every optional parameter that is not received by the endpoint is let undefined
Migration guide to 1.0.0 [available here](https://cloudflare.github.io/itty-router-openapi/migrating-to-1.0/)
